### ISSUE TITLE
Som

### ISSUE THREAD

**Issue by paul-git** [instacart/TrueTime.swift#12]
Hey there,

first of all, thank you for this great library! 
I´m all new to swift and I´m using swift 3. It seems that (maybe only in swift 3) your example for a callback is wrong:

```
// To block waiting for fetch, use the following:
client.retrieveReferenceTime { result in
    switch result {
        case let .Success(referenceTime):
            let now = referenceTime.now()
        case let .Failure(error):
            print("Error! \(error)")
    }
}
```

should be with lower case `.success` and `.failure`

I hope here is the right place to post it :)

Thanks again,
Paul

PS: I don´t know how to change the title :(

**Comment by msanders** [comment]
Thanks!
