### ISSUE TITLE
How to get notified every time there's a new time?

### ISSUE THREAD

**Issue by scottybe** [instacart/TrueTime.swift#15]
First, let me say that this is great!

The Android RX version can be subscribed to so that a function gets called every time (or at least the first time) a new "true time" is established. Is something like that possible in the iOS version? If not, what's the best way to do it?

Also, is the iOS version "full NTP" (instead of SNTP) like the Android RX version? If not, are there plans for that?

Thanks!

**Comment by msanders** [comment]
@scottybe Thanks, glad you like the library!

Yep, TrueTime by default uses full NTP when subscribing to `fetchIfNeeded`. You can also use SNTP by passing a [`first`](https://github.com/instacart/TrueTime.swift/blob/db0b35629bf5df29186aa89976e1aa92a7d18377/Sources/TrueTime.swift#L76) callback to the same method.

Currently there's no such mechanism to get notified each time a new network time is established, instead each `ReferenceTime` is automatically updated in the background at regular intervals (currently defaults to [~8 minutes](https://github.com/instacart/TrueTime.swift/blob/db0b35629bf5df29186aa89976e1aa92a7d18377/Sources/TrueTime.swift#L143)).

**Comment by scottybe** [comment]
Thanks for the quick response!

Do I understand correctly that fetchIfNeeded will "wait" for a new ntp time to be established before returning if it's currently in progress?

Also, if I _wanted_ to get notified when ReferenceTime is updated in the background, where would I need to insert postNotificationName:object: ? (That would be a nice addition, even if it deviates from the Android version!) My app sometimes has a precise countdown in progress that I would like to update whenever it is off.)

**Comment by msanders** [comment]
> Do I understand correctly that fetchIfNeeded will "wait" for a new ntp time to be established before returning if it's currently in progress?

Yes, that's right. It's a blocking call.

> Also, if I wanted to get notified when ReferenceTime is updated in the background, where would I need to insert postNotificationName:object: ?

Not a bad idea. You could probably add something like that [here](https://github.com/instacart/TrueTime.swift/blob/db0b35629bf5df29186aa89976e1aa92a7d18377/Sources/NTPClient.swift#L224).
