### ISSUE TITLE
Which version is recommended for swift 2.3?

### ISSUE THREAD

**Issue by douglasjunior** [instacart/TrueTime.swift#16]
I tested version 3.1.0, but I had some compilation errors.

**Comment by msanders** [comment]
3.1.0 should support 2.3 on the latest Xcode. There is also a `swift-2` branch with one backported change (support for configuring the polling interval).

**Comment by douglasjunior** [comment]
Thanks for answering.

I am using Xcode 7.3 (Unfortunately Xcode 8 gives me a problem), see the errors below.

![captura de tela 2016-12-28 as 08 46 30](https://cloud.githubusercontent.com/assets/1512341/21520196/c6155824-ccd9-11e6-9d28-995d4dd67b15.png)

1. /.../Pods/TrueTime/Sources/HostResolver.swift:77:74: Cannot force unwrap value of non-optional type 'String'

2. /.../Pods/TrueTime/Sources/HostResolver.swift:83:34: Nil is not compatible with expected argument type 'CFAllocatorCopyDescriptionCallBack' (aka '@convention(c) UnsafePointer<()> -> ImplicitlyUnwrappedOptional<Unmanaged<CFString>>')

**Comment by msanders** [comment]
Ah, yeah. Unfortunately Xcode 8 introduced breaking changes with Swift 2.3; there doesn't seem to be a way to support both 8 and 7. I'd recommend upgrading Xcode and changing the project settings to point to the Swift 2.3 compiler.

**Comment by douglasjunior** [comment]
I will plan the migration in the future. Thanks for the attention. 😃
