### ISSUE TITLE
Can't install via cocoapods

### ISSUE THREAD

**Issue by Sukhrob** [instacart/TrueTime.swift#17]
I was unable to install the library via cocoapods. I am using XCode 8 and Swift 3. It says "[!] Unable to find a specification for `TrueTime (~> 4.0)`"

**Comment by msanders** [comment]
Hi @Sukhrob

This seems to be working for me. Have you tried running `pod repo update` against the master Cocoapods repo?

**Comment by jtlthe2** [comment]
This worked for me! Thanks, @msanders.
