### ISSUE TITLE
How does detect TrueTimeClient is started ?

### ISSUE THREAD

**Issue by Darktt** [instacart/TrueTime.swift#18]
My class will initial TrueTimeClient object in class init(),
it will start every time, but it can not start second time,
how to detect client is started ?

Current use version 3.1.0

**Comment by msanders** [comment]
@Darktt: Can you elaborate on your question? Maybe some example code?

**Comment by Darktt** [comment]
Start client code:

``` swift
var pool: Array<NSURL> = []
pool.append(NSURL(string: "tock.stdtime.gov.tw")!)
pool.append(NSURL(string: "watch.stdtime.gov.tw")!)
pool.append(NSURL(string: "time.stdtime.gov.tw")!)
pool.append(NSURL(string: "clock.stdtime.gov.tw")!)
pool.append(NSURL(string: "tick.stdtime.gov.tw")!)

let client = TrueTimeClient.sharedInstance
client.start(hostURLs: pool)
```

how does detect is started or stop it.

**Comment by msanders** [comment]
@Darktt: You can use the `fetchIfNeeded` or `TrueTimeUpdated` notification to determine whether a time has been fetched. I've added a section on the README documenting this now: https://github.com/instacart/TrueTime.swift#notifications.

It's only necessary to start a client once (it will start/stop automatically based on network conditions), but you can manually stop it with the [pause](https://github.com/instacart/TrueTime.swift/blob/dcceef6c6161809ffc97e895a4e5fc2078082f59/Sources/TrueTime.swift#L71) method.
