### ISSUE TITLE
Any way to set servers yourself?

### ISSUE THREAD

**Issue by dkcas11** [instacart/TrueTime.swift#23]
Hey, i was wondering if it is possible to set your servers yourself?

I would like to retrieve the same UTC time format each time since i need to sort by timestamps. Or does TrueTime already retrieve the same format/zone each time?

Thanks for the library, it seems kinda easy to use :)

**Comment by msanders** [comment]
Hi @dkcas11,

The [start](https://github.com/instacart/TrueTime.swift/blob/86fc5eda625e8858cbc88610873f62e1217a0efc/Sources/TrueTime.swift#L67) method takes an array of host URLs, which can be set to an NTP server of your choice.

Times are sent back as `NSDate` values, which are just unix timestamps, so no need to worry about formatting issues or time zone conversions - sorting should work as expected.

**Comment by dkcas11** [comment]
Oh, totally forgot to reply. Thanks, that seems quite easy :) 
The problem i am facing, is that i want a universal timestamp, that is the same no matter where on earth you'd be. This is just for backend purposes, so the user will never know. 
Will the time i receive, then always be the same, no matter the time zone?

**Comment by msanders** [comment]
@dkcas11: Sorry for the delay. That is correct, it's a unix timestamp independent of timezone.
