### ISSUE TITLE
xcode 8.3 swift 3.1 warning

### ISSUE THREAD

**Issue by otymartin** [instacart/TrueTime.swift#24]
@msanders 
` self.init(whole: ValueType(UInt64(time.tv_sec + secondsFrom1900To1970)),`
 ` '+' is deprecated, mixed type addition is deprecated. please use explicit type conversion`

**Comment by msanders** [comment]
Thanks @otymartin. I've pushed a fix, will be tagging shortly.

**Comment by otymartin** [comment]
@msanders very nice! thanks :)
