### ISSUE TITLE
Swift not supported

### ISSUE THREAD

**Issue by martinobonfiglioli** [instacart/TrueTime.swift#32]
I'm trying to integrate True Time in my Obj-c .framework

I manually added the files to my project but I have this issue on build

> Check dependencies
> 
> Swift is not supported for static libraries.

Is there any way to avoid this issue or is there an Obj-c version of this library?

Thanks.

**Comment by afedor** [comment]
- Sometimes restarting Xcode fixes this issue
- If not, how did you compile TrueTime? Make sure it really is a framework and not a static library.  If you used CocoaPods, make sure the "use_frameworks!" flag is set.

**Comment by msanders** [comment]
@martinobonfiglioli: Swift frameworks cannot be generated statically by Xcode as far as I'm aware. To integrate with an ObjC framework you'll need to convert it to be a dynamic lib.
