### ISSUE TITLE
Proposed fix for warning: '+' is deprecated: Mixed-type addition is deprecated

### ISSUE THREAD

**Issue by dsrspro** [instacart/TrueTime.swift#34]
When using TrueTime in Xcode I have been receiving the following warning:

`'+' is deprecated: Mixed-type addition is deprecated. Please use explicit type conversion.`

The warning is found in: `NTPExtensions.swift` on line: 62.  The original code for that line is:
`self.init(whole: ValueType(UInt64(time.tv_sec + secondsFrom1900To1970)),`

By defining each side if the equation with `UInt64()` the warning disappears.

The new code should look like this:

`self.init(whole: ValueType(UInt64(time.tv_sec) + UInt64(secondsFrom1900To1970)),`

I hope this simple change is beneficial to making the overall code and developer experience even better.

**Comment by msanders** [comment]
@dsrspro: Makes sense. Can you put this up in a PR?

**Comment by kitefaster** [comment]
Any idea on when the next version of TrueTime will be released?
