### ISSUE TITLE
[Xcode 9 - 32bit devices] fatal error: Not enough bits to represent a signed value

### ISSUE THREAD

**Issue by useeless37** [instacart/TrueTime.swift#37]
this line crashes:

`self.init(whole: ValueType(UInt64(time.tv_sec + secondsFrom1900To1970)),
`

in 

```
extension NTPTimevalConvertible {
    init(timeSince1970 time: timeval) {
        precondition(time.tv_sec >= 0 && time.tv_usec >= 0, "Time must be positive \(time)")
        self.init(whole: ValueType(UInt64(time.tv_sec + secondsFrom1900To1970)),
                  fraction: ValueType(UInt64(time.tv_usec) * UInt64(1<<32 / USEC_PER_SEC)))
    }

    ...
}
```

note:
private let secondsFrom1900To1970: Int64 = ((365 * 70) + 17) * 24 * 60 * 60

**Comment by useeless37** [comment]
ok its fixed in https://github.com/instacart/TrueTime.swift/issues/34

**Comment by useeless37** [comment]
will use

`pod 'TrueTime', :git => 'https://github.com/instacart/TrueTime.swift.git', :commit => 'c4d863b0c8984a70e102990d8fd0d5e2d084560d'`

for now until released

**Comment by warpling** [comment]
Just started getting hundreds of iPhone 5c crashes. This explains it!

**Comment by msanders** [comment]
This fix is now included in the latest release (4.1.4).

**Comment by warpling** [comment]
Thank you Michael!

**Comment by nicferretti** [comment]
Using version 4.1.5 and this issue still arises
