### ISSUE TITLE
iOS target marked as macOS

### ISSUE THREAD

**Issue by flagoworld** [instacart/TrueTime.swift#42]
In TrueTime xcodeproj, the iOS framework target has:

Base SDK: No SDK
Supported Platforms: macOS

I believe this should be:

Base SDK: Latest iOS
Supported Platforms: iOS

The architectures change from intel to arm when those are properly configured.

**Comment by acrookston** [comment]
Thanks I was wondering why dependencies were building for x86 and not arm :) I've added a PR to fix this
