### ISSUE TITLE
Swift 4.1 compile errors

### ISSUE THREAD

**Issue by YuriiTrach** [instacart/TrueTime.swift#44]
Tried to use the latest version with cocoapods and this what I get:
NTPExtensions.swift:50:22: 'toIntMax()' is unavailable
NTPExtensions.swift:55:25: 'toIntMax()' is unavailable
NTPExtensions.swift:67:23: 'toIntMax()' is unavailable
TrueTime.swift:54:50: Let 'defaultTimeout' is private and cannot be referenced from a default argument value
TrueTime.swift:55:44: Let 'defaultMaxRetries' is private and cannot be referenced from a default argument value
TrueTime.swift:56:48: Let 'defaultMaxConnections' is private and cannot be referenced from a default argument value
TrueTime.swift:57:44: Let 'defaultMaxServers' is private and cannot be referenced from a default argument value
TrueTime.swift:58:49: Let 'defaultNumberOfSamples' is private and cannot be referenced from a default argument value
TrueTime.swift:59:55: Let 'defaultPollInterval' is private and cannot be referenced from a default argument value

Any ideas what's wrong?

**Comment by pipacs** [comment]
Looks like it's been fixed in master -- could we please get a new release.

**Comment by artemmihelson** [comment]
I am getting the same error. When to expect the new version?

**Comment by artemmihelson** [comment]
By the way, anyone experiencing this issue. You can temporary avoid by selecting Swift 3.2 as a Swift Language version in Pods -> Targets -> TrueTime -> Build Settings.

**Comment by miketsprague** [comment]
If you're using cocoapods...
It was updated to Swift 4 in October, but the podspec has yet to be updated.  You have to point the pod at the latest commit

```ruby
 pod 'TrueTime', :git => 'https://github.com/instacart/TrueTime.swift', :commit => '8aadebabe2590d6ab295c390df5bbc109b346348'
```

**Comment by sirioz** [comment]
Please is it possible to update the podspec and set a new tag with the latest commit?
It would be very important for the Swift4 compatibility.

**Comment by Funi1234** [comment]
+1 @sirioz. I have TrueTime as a dependancy in a podspec and cannot specify a commit to or branch. It must be a version.

**Comment by Usman4Github** [comment]
hi when will you upload/commit proper code
