### ISSUE TITLE
XCode9 support

### ISSUE THREAD

**Issue by fvisticot** [instacart/TrueTime.swift#47]
Trying to use this pod with objc/XCode9
I get the following error.
Can you please provide a new compatible version ?

The targets “Result” and “TrueTime” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.

**Comment by acrookston** [comment]
Can you confirm this is not Carthage issue, assuming you use Carthage you might have to specify build toolchain or clear the carthage caches and rebuild.

**Comment by dhavalshreyas** [comment]
This must be fixed now.
