### ISSUE TITLE
Unable to access "now" property of NTPReferenceTime 

### ISSUE THREAD

**Issue by pregno** [instacart/TrueTime.swift#48]
Hi,

After the update to Swift 4.0 I'm getting trouble retrieving the value from 
`NSDate *now = [[client referenceTime] now];`

The compiler says:
`No visible @interface for 'NTPReferenceTime' declares the selector 'now'`

If I put an `@objc` on the now property everything will work.

I'm wondering if I did something wrong with the setup or if the `@objc` is really needed.

Thanks

**Comment by msanders** [comment]
Thanks @pregno, looks like this was missed in the Swift 4 migration. Including a fix for next release.
