### ISSUE TITLE
Can you make it work with cocoapods?

### ISSUE THREAD

**Issue by tuyendv2** [instacart/TrueTime.swift#5]
Can you make it work with cocoapods?

**Comment by msanders** [comment]
We don't currently support Cocoapods, but if you want to add an external podspec we'll link to it from the README.

**Comment by warpling** [comment]
@msanders can I ask the reasoning for not supporting Cocoapods?

**Comment by msanders** [comment]
We don't use it internally and didn't want to add additional overhead in maintenance. But if people need it to use the project we can add support for it.

**Comment by warpling** [comment]
As a build-system-inept developer with a project dependent on Cocoapods the ease of a pod makes me much more likely to use a library but if I'm a minority and the overhead is too much I understand!
