### ISSUE TITLE
Please update cocoapod version

### ISSUE THREAD

**Issue by gloryluu** [instacart/TrueTime.swift#52]

**Comment by edwardmp** [comment]
There is no newer release (tag) than the one in CocoaPods, but a new release should be made, since Swift 4 support is currently missing in v4.1.5, but is present in the master branch.

Temporary solution:
` pod 'TrueTime', git: 'https://github.com/instacart/TrueTime.swift'`

**Comment by EsSpectacularrr** [comment]
Another fix is to change the swift version to 3.2 in the pods project

**Comment by acecilia** [comment]
Please, update the cocoapod version @msanders

**Comment by mhhashim** [comment]
I i have a library which uses TrueTime , now i cannot add dependancy using branch in podspec.
Please add cocoapod  version with swift4

**Comment by msanders** [comment]
Sorry for the delay, this should be fixed now.
