### ISSUE TITLE
Can't resume after pausing

### ISSUE THREAD

**Issue by Benzoate** [instacart/TrueTime.swift#54]
There's a pause function, it seems to stop the polling timer and halts reachability which is what I’d like to do when my app is backgrounded. Unfortunately there doesn't appear to be a way to resume the poll timer, since the start function ultimately asserts that the reachability callback hasn’t been already initialised.

It’d be great if either the library (optionally) responded to `UIApplicationDidEnterBackground` / `UIApplicationWillEnterForeground` events, or you could provide a method of resuming from a paused state. Thank you.

**Comment by scottybe** [comment]
I think this is a bug. It goes away if you add "self.reachability.callback = nil" in the pause function of NTPClient, then you can successfully call the start function again. Hopefully the writers can tell us if that's the correct solution!
