### ISSUE TITLE
When using carthage, the generated framework has an external dependency: Sources/CTrueTime/*.h

### ISSUE THREAD

**Issue by acecilia** [instacart/TrueTime.swift#57]
I added TrueTime to my project, using Carthage.

I did not add the folder "Checkouts" to source control.

Steps to reproduce:
- Remove the "Checkouts" folder.
- Build your project.

Expected:
- My project builds correctly, using the TrueTime carthage generated framework.

Reality:
- Xcode drops the error: Missing required module 'CTrueTime'.

Troubleshooting: if the file Sources/CTrueTime/*.h stays in the "Checkouts" folder, everything is fine. If it is not, the CTrueTime module can not build.

**Comment by pziemkowski** [comment]
Hello, is there any progress on this one? It's still an issue

**Comment by Dimon70007** [comment]
its strange. but i have found that for compiling another framework, that depends on TrueTime.framework needs to be available path to project with `Soruces/CTrueTime` where have been compiled TrueTime.framework. it looks like hard link to CTrueTime module

**Comment by sungjin0213** [comment]
Still issue for me on version 5.0.0 using Carthage.
