### ISSUE TITLE
Update dependency versions

### ISSUE THREAD

**Issue by raysarebest** [instacart/TrueTime.swift#66]
This module currently declares a dependency on [Result](https://github.com/antitypical/Result) version 4.0 in the podspec. However, this is out-of-sync with the Cartfile, which doesn't pin a specific version. Result has since been updated to 4.1, and Result 4.0 doesn't compile with Xcode 10.2 and Swift 5. Other modules can't depend on this project via CocoaPods and use Swift 5 until the podspec is updated to either not depend on a specific version, or to specifically depend on Result 4.1. Likewise, some dependencies declared in `Cartfile.private` have older versions pinned in `Cartfile.resolved`, causing them to fail to compile in Xcode 10.2

**Comment by acrookston** [comment]
Carthage locks the version in `Cartfile.resolved` where it's set to `4.0.0`. Can you explain in more detail the problem you have? Also feel free to post a PR if you have changes, it's usually faster to get a change through that way. https://github.com/instacart/TrueTime.swift/blob/master/Cartfile.resolved#L3

**Comment by raysarebest** [comment]
If you make a new, blank Swift 5 project and make a Podfile with these contents,:

```ruby
platform :ios, '12.2'

target 'Your Target Name' do
    pod 'TrueTime'
end
```

Your new project will fail to compile because the version of Result that is uses fails to compile under Swift 5. The version of the Result library this uses should be updated to the latest one, which works with Swift 5. Alternatively, this module can be converted to using Swift 5's native `Result` type and the dependency can be dropped

Either way, I'll work on this a bit and see if I can't get a PR made sometime soon

**Comment by dhavalshreyas** [comment]
Thanks @raysarebest . This should be fixed now, please file a new issue if it's not.
